Fix compilation error
This BOLT commit causes a compilation error for me:
https://github.com/facebookincubator/BOLT/commit/002d2367f9996f8faa9ef512af5491c45c12a44a

```
llvm/lib/Target/X86/Disassembler/X86Disassembler.cpp:271:5: error: constant expression evaluates to 256 which cannot be narrowed to type 'uint8_t' (aka 'unsigned char') [-Wc++11-narrowing]
    ALL_REGS
    ^~~~~~~~
llvm/lib/Target/X86/Disassembler/X86DisassemblerDecoder.h:389:3: note: expanded from macro 'ALL_REGS'
  REGS_16BIT          \
  ^~~~~~~~~~
llvm/lib/Target/X86/Disassembler/X86DisassemblerDecoder.h:132:3: note: expanded from macro 'REGS_16BIT'
  ENTRY(R15W)
  ^~~~~~~~~~~
llvm/lib/Target/X86/Disassembler/X86Disassembler.cpp:269:18: note: expanded from macro 'ENTRY'
                 ^~~~~~
llvm/lib/Target/X86/Disassembler/X86Disassembler.cpp:271:5: note: insert an explicit cast to silence this issue
    ALL_REGS
    ^~~~~~~~
llvm/lib/Target/X86/Disassembler/X86DisassemblerDecoder.h:389:3: note: expanded from macro 'ALL_REGS'
  REGS_16BIT          \
  ^~~~~~~~~~
llvm/lib/Target/X86/Disassembler/X86DisassemblerDecoder.h:132:3: note: expanded from macro 'REGS_16BIT'
  ENTRY(R15W)
  ^~~~~~~~~~~
llvm/lib/Target/X86/Disassembler/X86Disassembler.cpp:269:18: note: expanded from macro 'ENTRY'
                 ^~~~~~
```

It looks like the issue is that the original LLVM commit updated llvmRegnums to be a MCPhysReg (uint16_t), but the BOLT cherry-pick of this commit keeps it as a uint8_t.